//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BombDefuse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BombDefuse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DALES
        ///DEALS
        ///LADES
        ///LASED
        ///LEADS
        ///SLADE.
        /// </summary>
        internal static string LeadsWordCombinations {
            get {
                return ResourceManager.GetString("LeadsWordCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17
        ///79
        ///3
        ///16
        ///192
        ///256
        ///9524
        ///0
        ///6
        ///148.
        /// </summary>
        internal static string mathGeekAnswers {
            get {
                return ResourceManager.GetString("mathGeekAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5*3*1+4/1-2
        ///71+56/7
        ///slove for x  x+2=5
        ///8/2*(2+2)
        ///576/3
        ///8*32
        ///9524/1
        ///5*9*74*0*3
        ///2:3 is the same as 4:?
        ///half of 296
        ///.
        /// </summary>
        internal static string mathGeekEquations {
            get {
                return ResourceManager.GetString("mathGeekEquations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARETS
        ///ASTER
        ///EARST
        ///RATES
        ///REAST
        ///RESAT
        ///STARE
        ///STEAR
        ///STRAE
        ///TARES
        ///TASER
        ///TEARS
        ///TERAS.
        /// </summary>
        internal static string TearsWordCombinations {
            get {
                return ResourceManager.GetString("TearsWordCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADE
        ///DATER
        ///DERAT
        ///RATED
        ///TARED
        ///TREAD.
        /// </summary>
        internal static string TradeWordCombinations {
            get {
                return ResourceManager.GetString("TradeWordCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADE
        ///LEADS
        ///TEARS.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
